//
// Created by Иван on 10/22/2024.
//

#ifndef MAGNETTOPRJCT_NAMESNCONSTANTS_H
#define MAGNETTOPRJCT_NAMESNCONSTANTS_H

const int SQUARE_ELEMENT_NODE_COUNT = 4;
const int TRIANGULAR_ELEMENT_NODE_COUNT = 3;


#endif //MAGNETTOPRJCT_NAMESNCONSTANTS_H
